# ---------- Base ----------
FROM node:22-alpine AS base

WORKDIR /app

COPY package*.json ./

# ---------- Dependencies ----------
FROM base AS deps

RUN npm install

# ---------- Development ----------
FROM deps AS development

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]

# ---------- Build ----------
FROM deps AS build

COPY . .

RUN npm run build

# ---------- Production ----------
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev

COPY --from=build /app/dist ./dist

EXPOSE 5000

CMD ["node", "dist/server.js"]