services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev

    container_name: url-shortener-backend

    restart: unless-stopped

    env_file:
      - ../.env

    ports:
      - "5000:5000"

    volumes:
      - ../:/app
      - /app/node_modules

    depends_on:
      - mongo
      - redis

    networks:
      - url-shortener-network

  mongo:
    image: mongo:8

    container_name: url-shortener-mongo

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

    volumes:
      - mongo-data:/data/db

    networks:
      - url-shortener-network

  redis:
    image: redis:8-alpine

    container_name: url-shortener-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - url-shortener-network

volumes:
  mongo-data:
  redis-data:

networks:
  url-shortener-network: