FROM node:22-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm ci


FROM deps AS builder

WORKDIR /app

COPY . .

RUN npm run build && echo "===== BUILD OUTPUT =====" && ls -la /app/dist && echo "===== SERVER.JS =====" && ls -la /app/dist/server.js


FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 5000

USER node

CMD ["node", "dist/server.js"]